CREATE DATABASE HR_PROJECT
USE HR_PROJECT

SELECT TOP 5 * FROM HRDataset_v14
SELECT COUNT(*) FROM HRDataset_v14


--AUTO-CREATE EACH TABLE FROM DATA
SELECT DISTINCT DEPARTMENT AS DEPTNAME INTO DEPARTMENTS FROM HRDataset_v14
SELECT DISTINCT POSITION AS POSITIONTITLE INTO POSITIONS FROM HRDataset_v14
SELECT DISTINCT MANAGERID, MANAGERNAME INTO MANAGERS FROM HRDataset_v14 WHERE MANAGERID IS NOT NULL
SELECT DISTINCT RECRUITMENTSOURCE INTO RECRUITMENTSOURCES FROM HRDataset_v14

-- ADD ID COLUMN + PRIMARY KEYS
ALTER TABLE DEPARTMENTS ADD DEPTID INT IDENTITY(1,1)
ALTER TABLE DEPARTMENTS ADD PRIMARY KEY (DEPTID)

ALTER TABLE POSITIONS ADD POSITIONID INT IDENTITY(1,1)
ALTER TABLE POSITIONS ADD PRIMARY KEY (POSITIONID)

ALTER TABLE RECRUITMENTSOURCES ADD SOURCEID INT IDENTITY(1,1)
ALTER TABLE RECRUITMENTSOURCES ADD PRIMARY KEY (SOURCEID)

ALTER TABLE MANAGERS ALTER COLUMN MANAGERID INT NOT NULL
ALTER TABLE MANAGERS ADD PRIMARY KEY (MANAGERID)

-- CHECK
SELECT * FROM DEPARTMENTS
SELECT * FROM POSITIONS
SELECT * FROM MANAGERS
SELECT * FROM RECRUITMENTSOURCES


--DATA CLEANING
SELECT
    H.EMPID,
    H.EMPLOYEE_NAME AS EMPLOYEENAME,
    H.SEX,
    H.MARITALDESC,
    H.RACEDESC,
    H.STATE,
    D.DEPTID,
    P.POSITIONID,
    H.MANAGERID,
    RS.SOURCEID,
    H.SALARY,
    H.EMPLOYMENTSTATUS,
    H.TERMREASON
INTO EMPLOYEES
FROM HRDATASET_V14 H
LEFT JOIN DEPARTMENTS D ON H.DEPARTMENT = D.DEPTNAME
LEFT JOIN POSITIONS P ON H.POSITION = P.POSITIONTITLE
LEFT JOIN RECRUITMENTSOURCES RS ON H.RECRUITMENTSOURCE = RS.RECRUITMENTSOURCE

ALTER TABLE EMPLOYEES ALTER COLUMN EMPID INT NOT NULL
ALTER TABLE EMPLOYEES ADD PRIMARY KEY (EMPID)

SELECT
    EMPID,
    PERFORMANCESCORE,
    ENGAGEMENTSURVEY,
    EMPSATISFACTION,
    ABSENCES,
    DAYSLATELAST30
INTO PERFORMANCEREVIEWS
FROM HRDATASET_V14

ALTER TABLE PERFORMANCEREVIEWS ALTER COLUMN EMPID INT NOT NULL
ALTER TABLE PERFORMANCEREVIEWS ADD PRIMARY KEY (EMPID)

SELECT COUNT(*) FROM EMPLOYEES
SELECT COUNT(*) FROM PERFORMANCEREVIEWS
SELECT TOP 5 * FROM EMPLOYEES
 

ALTER TABLE EMPLOYEES ADD CONSTRAINT FK_DEPT FOREIGN KEY (DEPTID) REFERENCES DEPARTMENTS(DEPTID)
ALTER TABLE EMPLOYEES ADD CONSTRAINT FK_POS FOREIGN KEY (POSITIONID) REFERENCES POSITIONS(POSITIONID)
ALTER TABLE EMPLOYEES ADD CONSTRAINT FK_SRC FOREIGN KEY (SOURCEID) REFERENCES RECRUITMENTSOURCES(SOURCEID)
ALTER TABLE PERFORMANCEREVIEWS ADD CONSTRAINT FK_EMP FOREIGN KEY (EMPID) REFERENCES EMPLOYEES(EMPID)


SELECT * FROM SYS.FOREIGN_KEYS




-- HEADCOUNT BY DEPARTMENT
SELECT D.DEPTNAME, COUNT(*) AS HEADCOUNT
FROM EMPLOYEES E JOIN DEPARTMENTS D ON E.DEPTID = D.DEPTID
GROUP BY D.DEPTNAME ORDER BY HEADCOUNT DESC
 
-- ATTRITION RATE BY DEPARTMENT
SELECT D.DEPTNAME,
    COUNT(*) AS TOTAL,
    SUM(CASE WHEN E.EMPLOYMENTSTATUS != 'Active' THEN 1 ELSE 0 END) AS LEFT_COUNT,
    ROUND(100.0 * SUM(CASE WHEN E.EMPLOYMENTSTATUS != 'Active' THEN 1 ELSE 0 END) / COUNT(*), 1) AS ATTRITION_PCT
FROM EMPLOYEES E JOIN DEPARTMENTS D ON E.DEPTID = D.DEPTID
GROUP BY D.DEPTNAME ORDER BY ATTRITION_PCT DESC
 
-- AVG SALARY BY DEPARTMENT
SELECT D.DEPTNAME, ROUND(AVG(E.SALARY), 0) AS AVG_SALARY
FROM EMPLOYEES E JOIN DEPARTMENTS D ON E.DEPTID = D.DEPTID
GROUP BY D.DEPTNAME ORDER BY AVG_SALARY DESC
 
-- SALARY BY GENDER, SAME POSITION (PAY EQUITY)
SELECT P.POSITIONTITLE, E.SEX, ROUND(AVG(E.SALARY), 0) AS AVG_SALARY
FROM EMPLOYEES E JOIN POSITIONS P ON E.POSITIONID = P.POSITIONID
GROUP BY P.POSITIONTITLE, E.SEX
 
-- RECRUITMENT SOURCE VS ATTRITION
SELECT RS.RECRUITMENTSOURCE,
    COUNT(*) AS HIRED,
    ROUND(100.0 * SUM(CASE WHEN E.EMPLOYMENTSTATUS != 'Active' THEN 1 ELSE 0 END) / COUNT(*), 1) AS ATTRITION_PCT
FROM EMPLOYEES E JOIN RECRUITMENTSOURCES RS ON E.SOURCEID = RS.SOURCEID
GROUP BY RS.RECRUITMENTSOURCE ORDER BY HIRED DESC
 
-- TOP 10 ABSENTEES
SELECT TOP 10 E.EMPLOYEENAME, P.ABSENCES
FROM EMPLOYEES E JOIN PERFORMANCEREVIEWS P ON E.EMPID = P.EMPID
ORDER BY P.ABSENCES DESC

---- DIVERSITY: GENDER SPLIT BY DEPARTMENT
SELECT D.DEPTNAME, E.SEX, COUNT(*) AS CNT
FROM EMPLOYEES E JOIN DEPARTMENTS D ON E.DEPTID = D.DEPTID
GROUP BY D.DEPTNAME, E.SEX ORDER BY D.DEPTNAME
 
-- DIVERSITY: RACE SPLIT COMPANY-WIDE
SELECT RACEDESC, COUNT(*) AS CNT,
    ROUND(100.0 * COUNT(*) / (SELECT COUNT(*) FROM EMPLOYEES), 1) AS PCT
FROM EMPLOYEES GROUP BY RACEDESC ORDER BY CNT DESC
 